# Generated by Django 2.1.10 on 2019-08-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_mitute',
            new_name='time_minutes',
        ),
    ]
